### ISSUE TITLE
Configuring skrollr in apps config throws error

### ISSUE THREAD

**Issue by soosap** [thisissoon/angular-skrollr#10]
`// 1. configure skrollr in your apps config`
`var myApp = angular.module('myApp', []);`
`myApp.config(["snSkrollrProvider", function(snSkrollrProvider) {`
`snSkrollrProvider.config({ smoothScrolling: true, ... });`
`}]);`

This is the error message I get:
TypeError: object is not a function

Commenting this out, it works as it should. So the directive seems to work, just the configuration option fails.

**Comment by jamesjwarren** [comment]
It seems the documentation is not correct, please try setting the config like so:
`snSkrollrProvider.config = { smoothScrolling: true };`

You may then set any additional skrollr configuration options in this object. I'll update the docs.

**Comment by soosap** [comment]
Jap that works for me, thanks for the quick reply.
