### ISSUE TITLE
Few questions about code

### ISSUE THREAD

**Issue by rpCal** [thisissoon/angular-skrollr#14]
Hi, 
Greate job! I live much what you do!
I have question about your code. Im rly interested in your appoach. Why do you use .provider("snSkrollr") instead of use local controler in directive? You init the plugin on $document.read event?

**Comment by jamesjwarren** [comment]
Glad to hear it may prove useful for you. We're using an angular provider so we can expose skrollr configuration options at the angular config stage. This allows skrollr to be setup differently for different applications, making it easily reusable.

Check out this angular doc for more info:
https://docs.angularjs.org/guide/providers

**Comment by rpCal** [comment]
Thanks! 
You have right. Angular docs: "You should use the Provider recipe only when you want to expose an API for application-wide configuration that must be made before the application starts.", good to know this.
Great job. Im start use it :)
