### ISSUE TITLE
Module/App configuration incorrect package call

### ISSUE THREAD

**Issue by ghost** [thisissoon/angular-skrollr#22]
I was trying to set up my app.config based off of the Readme and after some frustration I got angular-skrollr integrated into my app. Despite the Readme stating that I needed to declare the package as `snSkrollrProvider` in my app.config, I could only get it to work with `sn.skrollr`. 

Does the Readme have an error in it?

**Comment by edoparearyee** [comment]
@bodieskate looks like some missing information in the read me. The module should injected into your app like so:

``` javascript
var myApp = angular.module('myApp', ["sn.skrollr"]);
```

We will update the docs
