### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by homerjam** [thisissoon/angular-skrollr#26]

**Comment by edoparearyee** [comment]
At the moment we don't publish our packages to npm but it's something we would like to do in the future. 

In the meantime you can install the package using npm with this command: `npm install thisissoon/angular-skrollr`

**Comment by KasperAndersson** [comment]
+1

**Comment by edoparearyee** [comment]
This package is now on npm, simply use `npm install angular-skrollr` to install.

**Comment by homerjam** [comment]
Thanks @edwardoparearyee !

**Comment by KasperAndersson** [comment]
Great @edwardoparearyee  :+1:
