### ISSUE TITLE
Angular v1.5.8 support

### ISSUE THREAD

**Issue by lbehnke** [thisissoon/angular-skrollr#38]
After upgrading from angular 1.4 to 1.5.8 the angular-skrollr stopped working. In fact, I am not sure whether it's the angular-skrollr itself or some transitive dependency that causes the problem.
Anyway,  v1.5.8 support would be great. Currently,  version 1.2 < 1.5 is supported.

**UPDATE**

Angular-skrollr _does_ support Angular 1.5.8 as far as I can tell. I had a glitch in my configuration. 
So, it's just the version info that should be updated.

**Comment by edoparearyee** [comment]
Fixed in #39

**Comment by edoparearyee** [comment]
v0.2.1 has been published on npm
